# Gunakan Node.js image yang ringan
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install all dependencies (including dev)
RUN npm install

# Copy the rest of the code
COPY . .

# Build Next.js project
RUN npm run build

# Expose the Next.js default port
EXPOSE 3000

# Jalankan Next.js di production mode
CMD ["npm", "run", "start"]
